name: Publish to NPM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.14.0'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies and verify
      run: |
        npm audit signatures

    - name: Publish package to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.key }}
